//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEAPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSVData
    {
        public int Serial { get; set; }
        public string Date { get; set; }
        public string Dept { get; set; }
        public string EmpId { get; set; }
        public string In1 { get; set; }
        public string Out1 { get; set; }
        public string In2 { get; set; }
        public string Out2 { get; set; }
        public string In3 { get; set; }
        public string Out3 { get; set; }
        public string In4 { get; set; }
        public string Out4 { get; set; }
        public string In5 { get; set; }
        public string Out5 { get; set; }
    }
}
