//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEAPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveStatus
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> QCL_In { get; set; }
        public Nullable<int> QCL_Out { get; set; }
        public Nullable<int> HCL { get; set; }
        public Nullable<int> FCL { get; set; }
        public Nullable<int> HML { get; set; }
        public Nullable<int> FML { get; set; }
        public Nullable<int> EL { get; set; }
        public string PresenceState { get; set; }
        public int EmployeeEmpId { get; set; }
        public double LWP { get; set; }
    }
}
