//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEAPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MEAPSDbEntities : DbContext
    {
        public MEAPSDbEntities()
            : base("name=MEAPSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attendance> Attendances { get; set; }
        public DbSet<CSVData> CSVDatas { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<ExceptionAttendance> ExceptionAttendances { get; set; }
        public DbSet<Holiday> Holidays { get; set; }
        public DbSet<LeaveApplication> LeaveApplications { get; set; }
        public DbSet<LeaveStatus> LeaveStatuses { get; set; }
        public DbSet<TimeException> TimeExceptions { get; set; }
        public DbSet<TabCtrl> TabCtrls { get; set; }
    }
}
